### ISSUE TITLE
... is not a fully qualified URL, please use App->internalRedirect() instead

### ISSUE THREAD

**Issue by voryzen** [friendica/docker#117]
Hi @nupplaphil ,

I'm actually still getting this issue (6124) with my friendica instance (red hot poker) via docker, traefik 2.2, nginx 1.17.10 (and the apache version) and mariadb 10.4.13.

Wasn't this fixed? or am I doing something wrong?

**Comment by voryzen** [comment]
@nupplaphil I am wanting to add Friendica to another project, aimed at easily deploying services for users... This is the issue holding me back..

Is there a way you fix this?

**Comment by nupplaphil** [comment]
Can you give me the full log excerpt? Do you use docker-compose?
I do need the full export because there are several possible places where such an error can occur.

I think it's more a Friendica upstream bug than because of docker itself, but I've to take a look into your log

Sorry, I'm currently a little bit busy, That's why my response time isn't the best atm ;-)

**Comment by voryzen** [comment]
Hi @nupplaphil, I do use docker-compose,

Unfortunately, I don't have the logs, because I've needed to do other work on the project and my Friendica attempt had to take a backseat.

I'll re-attempt a make, and I'll update it here.

I guess I really wanted to know, how this was fixed upstream, in the Friendica github., Because I'm unsure why this bug should effect a docker deployment

**Comment by nupplaphil** [comment]
OK, just add the logs here and I'll take a look.

@"how is that even possible":
**Short answer**: It's code, we're coders and humans, so failures are inevitable ;-)

**Long answer**:
Here you can see the exception root
https://github.com/friendica/friendica/blob/f10062dfdbacb48910482678d919ad37de57015f/src/Core/System.php#L215-L221

So in case the passed URL isn't fully qualified, the exception occurs. We do use this method all around the codebase to redirect requests. So there seems to be a particular situation where we don't have the fully qualified URL (inside the DB, because of a redirect, a coding-bug, IDK yet :) ) but we try to use it as it would be fully qualified. That's why the App crash.

**Comment by nupplaphil** [comment]
@voryzen did you try it again? Does it work now? :)

**Comment by voryzen** [comment]
> @voryzen did you try it again? Does it work now? :)

Hi @nupplaphil,
Thanks. I'm a big ff7 fan too.

I haven't had a chance yto get back to it. I'm still ironing out some issues with ViciLab.

As far as I know, a colleague has got it working, so when I get a chance, I'll compare our code.

I'll close this issue, and I'll reopen it if I (need to, and) can't work around it.
