### ISSUE TITLE
Automatically update docker images after release

### ISSUE THREAD

**Issue by nupplaphil** [friendica/docker#127]
If I do get a way to automatically fetch the Friendica releases, it would be possible to automatically create/update docker images based on this list. So this repo would automatically update itself with each new release and I'm no more necessary to permanently check it ;-) .. And a next followup would be to automatically create a PR in the official library in case of a new release (but step by step :-) )

Maybe with an event of the github releases. I know from nextcloud that there's a releases repository: https://download.nextcloud.com/server/releases/ which includes
- all "latest", stable and RC releases
- SHA256 / MD5 hash sums for checks

Calling for @tobiasd and @MrPetovan if you know a similar way for Friendica. This would be helpful in either case :-)

**Comment by MrPetovan** [comment]
Each release is tagged in the git repository, so retrieving the list of tags effectively gives you the full list of releases. We do not have the hash sum for downloads, but the release archive follows this pattern:
```
https://github.com/friendica/friendica/releases/download/<release>/friendica-full-<release>.tar.gz
```
But I'm not sure that's what you want.

**Comment by tobiasd** [comment]
No, the full archive does not follow that pattern ;) it is not automatically generated, and for a long time the archive was too large for the github filesize limitations. They must have make that restrictions on a larger file size, so that the archive could be uploaded the last time (when Wordpress changed something, so the upload to friendi.ca via WP was not possible...). But I think a more structured place to have for the archives for downloads would be nice.

At the moment the sha-sums are only avail-able at the downloads page at the homepage.

**Comment by nupplaphil** [comment]
@tobiasd  What about a "simple" File Service on friendi.ca for the releases? Am I thinking to simple or would that work, wouldn't it? Maybe @utzer can create a directory for it (like mapping the sub-dir `/release` on a readonly dir on the server)

**Comment by ben-utzer** [comment]
I can somehow map some folder on a webserver of mine, subfolder might be possible, would have to look into the setup of git.friendi.ca server, probably another subdomain would be nicer, so some subdomain of friendi.ca. 

Let me know when you need me to do something. Subdomain setup would need action by Heluecht (non mention because not needed to notify now). 

@nupplaphil Just our of curiosity, do we have some "bigger" server running with the docker image? I wonder how well it behaves with the typical 30-40 GB of data (10 G DB and rest in file storage).

**Comment by nupplaphil** [comment]
If a subdomain is nicer, I'll take it too :-) .. I "just" need a file-service with a complete release list (I think the last 3-4 releases are enough..) so I can fetch them from one resource.

The "opensocial.at" server is running on docker. I must confess I didn't do any checks so far, but it behaves similar to a normal setup, since all services (App & DB) & file-mounts are running on the same physical node (yet). I'm currently working on a kubernetes cluster (hetzner cloud). THERE we'll see how well it behaves with horizontal scaling :-)

**Comment by tobiasd** [comment]
We could have a look if gitea allows some kind of "additional directory" we could use?

**Comment by ben-utzer** [comment]
@nupplaphil OK, was just wondering if the delivered settings are good for a bit bigger node. Maybe the next time I do a setup I will set it up as docker, didn't think of that last week when I did migrate to a new VM with Nginx instead of Apache and PHP-FPM in addition. 

@tobiasd for me that is fine too, but if is just needs to be a webfolder with https I see easier ways then github, As said a folder under subdomain.friendi.ca would not be to hard to setup, just few lines in Nginx or Apache, depending where I add it.

**Comment by tobiasd** [comment]
We could create a subdirectory on git.friendi.ca, say "archives" or so and I could upload the full archives and the sha256 sum there. Then the upload problem with Wordpress would be "fixed" as well...

**Comment by ben-utzer** [comment]
> We could create a subdirectory on git.friendi.ca, say "archives" or so and I could upload the full archives and the sha256 sum there. If we don't need an directory indexing that would work out-of-the-box. Then the upload problem with Wordpress would be "fixed" as well...

Is there a webserver running? I think it is gitea serving the webpage, isn't it? But still we could run a webserver, nginx or lighttp, gitea (or whatever) is running on a different port that 80/443. You can just setup some webserver, preferable with the data in /srv/http and let me know, but again I need that running on a different domain the gitea. I can explain why I think so in some chat/Signal/call.

**Comment by tobiasd** [comment]
Gitea would then serve static files, hence no index. But as we only need a fixed name schema and the archive and sha-sum files, that would be sufficient.

**Comment by ben-utzer** [comment]
> Gitea would then serve static files, hence no index. But as we only need a fixed name schema and the archive and sha-sum files, that would be sufficient.

Not sure how/if gitea can do that. 

We can also spin up some nginx on that server, that then serves the static files and gitea dynamic stuff, with gitea serving / and nginx serving static files from /subfolder. 
Not sure if this can be accomplished by gitea completely, but maybe that is what you mean and know how to do. 

Another question, there was a time when I was told that we need TLS 1.0 for some strange service accessing the gitea, is that reason still present, otherwise I would like to disable TLS 1.0 for sure and maybe 1.1 as well. @nupplaphil @tobiasd do you remember the reason?

**Comment by tobiasd** [comment]
Could be [this handshake](https://git.friendi.ca/friendica/git.friendi.ca/issues/6) issue? And IIRC there was a problem with composer downloading one of the dependencies we host in the gitea instance.

**Comment by ben-utzer** [comment]
> Could be [this handshake](https://git.friendi.ca/friendica/git.friendi.ca/issues/6) issue? And IIRC there was a problem with composer downloading one of the dependencies we host in the gitea instance. But I cannot say if that problem still exist ;-)

Not sure, I thought I commented on the issue too. 

Maybe I will just remove the support for TLS 1.0 and 1.1 and see what breaks. I will announce that however.

**Comment by nupplaphil** [comment]
And here we go: https://files.friendi.ca :-) :-) thx !
