### ISSUE TITLE
2020.07-1 hotfix missing from dockerhub

### ISSUE THREAD

**Issue by jaywink** [friendica/docker#132]
Looks like there is a commit https://github.com/friendica/docker/commit/34e0bd306e569ef6b650d61f8c97bdef2a51d9d2 but the tag isn't available in dockerhub.

**Comment by nupplaphil** [comment]
https://github.com/docker-library/official-images/pull/8691
We're on it. I think few hours left :-)

**Comment by jaywink** [comment]
Ah right, didn't realize it goes through that process :) Thanks!

**Comment by nupplaphil** [comment]
the process is necessary because the Friendica Image is part of the offical docker image library and therefore has an additional process-step.
But the benefits are for example that we do have another quality check from official docker maintainers and the images are auto-created for almost any architecture (i386, mips, arm, ...) something I really appreciated in the past :-)

**Comment by nupplaphil** [comment]
@jaywink you can try it in a few hours I guess. The PR is merged, now the build has to get finished :). Therefore I'm closing this issue :) feel free to reopen it in case something is wrong
