### ISSUE TITLE
Use of undefined constant DB_UPDATE_VERSION

### ISSUE THREAD

**Issue by pedroponte** [friendica/docker#184]
I am trying to install friendica on docker and am getting this error in the installation page

Use of undefined constant DB_UPDATE_VERSION

- [ X ] I have searched open and closed issues for duplicates

### Steps to Reproduce

1.  configure docker
2.  use a mysql db as host (ie not a docker instance), by configuring the following parameters as specified in https://hub.docker.com/_/friendica
 MYSQL_HOST= xx.xx.xx.xx
      - MYSQL_DATABASE=xyz
      - MYSQL_USER=xyz
      - MYSQL_PASSWORD=xyz
3.  opened web installation page in browser

Actual Result:

PHP error in the first page
Use of undefined constant DB_UPDATE_VERSION

Expected Result:

No errors output in installation page

### Screenshots

![Screenshot 2022-01-12 at 12 06 36](https://user-images.githubusercontent.com/5510270/149137455-c6f71c9a-069c-43bb-8c13-4bcfe14e70b9.png)
![Screenshot 2022-01-12 at 12 09 26](https://user-images.githubusercontent.com/5510270/149137757-ce4193e6-c882-438b-8513-2ac8f9138f4d.png)

### Platform Info

Friendica Version: 

Docker image as of Jan 12th 2022

**Comment by nupplaphil** [comment]
@pedroponte 
This is unfortunately a regression of the current stable (2021.09) Friendica codebase.
Please use the current Release Candidate version (2021.12-rc), because it's "almost" released ;-) and this bug is fixed at https://github.com/friendica/friendica/pull/10891

`friendica:rc` is the right tag for it
