### ISSUE TITLE
How to check cron jobs?

### ISSUE THREAD

**Issue by ne20002** [friendica/docker#215]
Hi
I've set up my friendica with docker images and installed two versions of the fpm image, one for friendica and one for cron jabs as described in the examples.

Now this is what I get as output:
![grafik](https://user-images.githubusercontent.com/39007279/202855732-4a8a15ee-4d81-4f38-a362-7815e557e831.png)

This is how the similar setup for Nextcloud looks:
![grafik](https://user-images.githubusercontent.com/39007279/202855896-8479c311-5270-4797-9110-cdee51405260.png)

As I don't see and output for frinedica cron: how can I check if the cron jobs are working?

**Comment by MrPetovan** [comment]
There are a few ways:
- The main admin page will tell you if the worker wasn't ran in the last hour. It also features the number of delayed tasks and the current active queue in "Messages queues". If the left number isn't 0 and the right number fluctuates with time, you know it's working.
- Enable the Friendica log with level Notice or more verbose, you should see lines that start with "worker" instead of "index".
- If you have remote followers, publish a test post, and verify the delivery works in the post header (in the frio theme, the icon is either an hourglass if delivery is pending, a paper plane if delivery is ongoing, or a checkmark when it's done)
